### ISSUE TITLE
cant use shortcut key to open yazi in neovim

### ISSUE THREAD

**Issue by dev24hrs** [Kicamon/yazi.nvim#1]
Hi,
在哔哩哔哩上看到你的视频， 想尝试用yazi代替nvim-tree，但是在安装plugin之后无法使用快捷键调用yazi
手动输入 :Yazi 成功。
电脑：macos 
neovim：0.10.1
快捷键无冲突
checkhealth 无相关error
nvim log 日志无相关error
反复尝试几次之后 只能求助。。
感谢。

<img width="1500" alt="image" src="https://github.com/user-attachments/assets/b04ec12d-d87b-410a-8a69-7c62d3bc4ed6">

**Comment by Kicamon** [comment]
这个啊，快捷键不要写在config里边。这个插件配置了lazy,一开始没有触发就不会加载这个快捷键 。要么把这个快捷键写到一开始就加载的地方，要么就把`lazy = tue,`和`cmd = 'Yazi',`这两行删掉

**Comment by Kicamon** [comment]
是不是有个bug,只能打开一次hhh。有个api在0.10和0.11里的用法不一样
