### ISSUE TITLE
Can't open ":Yazi tabe"

### ISSUE THREAD

**Issue by Haaxenii** [Kicamon/yazi.nvim#2]
Error executing Lua callback: ...xenii/.local/share/nvim/lazy/yazi.nvim/lua/yazi/init.lua:89: attempt to call a nil val
ue                                                                                                                     
stack traceback:                                                                                                       
        ...xenii/.local/share/nvim/lazy/yazi.nvim/lua/yazi/init.lua:89: in function 'load_command'                     
        ...xenii/.local/share/nvim/lazy/yazi.nvim/lua/yazi/init.lua:109: in function <...xenii/.local/share/nvim/lazy/y
azi.nvim/lua/yazi/init.lua:105>

**Comment by Kicamon** [comment]
ok, now
